[package]
name = "browser-engineering"
version = "0.1.0"
edition = "2018"
authors = [
  "Seo Sanghyeon <sanxiyn@gmail.com>"
]

[[example]]
name = "http"

[dependencies]
rustls = "0.19"
webpki = "0.21"
webpki-roots = "0.21"
